### ISSUE TITLE
bug: calling contract results in Invalid params error message

### ISSUE THREAD

**Issue by irisdv** [xJonathanLEI/starknet-rs#508] opened 2023-11-29 10:36 UTC
While trying to call the aggregate function of a multicall contract deployed on mainnet : https://voyager.online/contract/0x01a87ac82de4c6e81dbfe5decf1f11d331366e1401e2b8e7ed342838ec49694f#readContract

Using starknet-rs and papyrus it results in the following error : `code: Unknown(-32602), message: "Invalid params"` but it works using Alchemy.

I initially published this issue in the Papyrus repository, but it seems the issue is not coming from there : https://github.com/starkware-libs/papyrus/issues/1451

Code to reproduce the issue, using the latest version of starknet-rs available on the repo : 

```rs
let calls: Vec<FieldElement> = vec![
        FieldElement::ONE, // size of the array of calls
        FieldElement::from_hex_be(
            "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7",
        )
        .unwrap(), // erc20 contract address
        selector!("balanceOf"),
        FieldElement::ONE, // size of the array
        FieldElement::from_hex_be(
            "0x061b6c0a78f9edf13cea17b50719f3344533fadd470b8cb29c2b4318014f52d3",
        )
        .unwrap(), // account address
    ];
    
    let provider = JsonRpcClient::new(HttpTransport::new(Url::parse(&conf.rpc.rpc_url).unwrap()));
    let call_result = provider
        .call(
            FunctionCall {
                contract_address: FieldElement::from_hex_be(
                    "0x01a87ac82de4c6e81dbfe5decf1f11d331366e1401e2b8e7ed342838ec49694f"
                ).unwrap(),
                entry_point_selector: selector!("aggregate"),
                calldata: calls,
            },
            BlockId::Tag(BlockTag::Latest),
        )
        .await;
    match call_result {
         Ok(result) => result,
        Err(e) => {
             println!("Error calling contract: {:?}", e);
             vec![]
        }
     }
```

**Comment by xJonathanLEI** [comment] 2023-12-05 17:25
Thanks for reporting. I'm curious though - if it works with Alchemy, why do you think this is not on Papyrus?

**Comment by Th0rgal** [comment] 2023-12-05 17:53
> starkware-libs/papyrus#1451

To be honest I don't know, Starkware said it is not a valid request but I think the node used by Alchemy (is it juno?) tries to be as flexible as possible to be compatible with everything.

**Comment by xJonathanLEI** [comment] 2023-12-06 05:20
See https://github.com/starkware-libs/papyrus/issues/1451#issuecomment-1842105365. Closing this now as I believe this is not a bug of `starknet-rs` but Papyrus. I haven't tested but I think you'll hit the exact same problem using other SDKs.

**Closed by xJonathanLEI** 2023-12-06 05:20 UTC
