### ISSUE TITLE
Problems compiling example on Ubuntu 20.04 server

### ISSUE THREAD

**Issue by rbdm-qnt** [xJonathanLEI/starknet-rs#332] opened 2023-03-19 19:09 UTC
After successfully compiling my application on a Ubuntu 22 VM, I'm trying to compile it on a Ubuntu 20 server. When I git clone the starknet-rs repository, go to /examples/starknet-cxx/ and compile following the commands "$ mkdir build && cd build
$ cmake -DCMAKE_BUILD_TYPE=Release .." I get the following error:

`
ubuntu@ip-xxx:~/proj/external/starknet-rs/examples/starknet-cxx/build$ sudo cmake -DCMAKE_BUILD_TYPE=Release ..
-- Rust Toolchain: stable-x86_64-unknown-linux-gnu
-- Rust Target: x86_64-unknown-linux-gnu
-- Using Corrosion as a subdirectory
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/ubuntu/proj/external/starknet-rs/examples/starknet-cxx/starknet-cxx/Cargo.toml
workspace: /home/ubuntu/proj/external/starknet-rs/Cargo.toml
CMake Error at _deps/corrosion-src/cmake/Corrosion.cmake:1488 (message):  
Crate starknet-cxx does not depend on cxx.
Call Stack (most recent call first): 
 starknet-cxx/CMakeLists.txt:2 (corrosion_add_cxxbridge)

-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/proj/external/starknet-rs/examples/starknet-cxx/CMakeFiles/CMakeOutput.log".
`

I've tried to wipe and set up the server again multiple times with no luck. I'm able to compile on my Ubuntu 22 VM but env variables and all files match. I'm using rustc 1.6.8 on the non-working VM, and 1.6.5 on the working VM.  I'm not 100% it's not a Ubuntu version issue. 

Any help or more detailed instructions on how to install the lib for Rust noobs would be greatly appreciated!

EDIT: I created a new Ubuntu 22 VM and tried doing a fresh install on that version, and it gives me the same problem.

EDIT 2: found a hacky workaround, I hardcoded my installed version of cxx into  _deps/corrosion-src/cmake/Corrosion.cmake at line 1486

**Comment by xJonathanLEI** [comment] 2023-03-20 01:56
Hi thanks for reporting. I guess as a first step it'd be helpful to set up CI for making sure the example compiles. If the CI works, there must be some way your setup is off; otherwise we can start looking into why the CI fails.

**Comment by rbdm-qnt** [comment] 2023-03-22 19:55
Have you tried spinning up a new VM and compiling the example?

**Comment by xJonathanLEI** [comment] 2023-07-03 13:15
Tried building and running the `starknet-cxx` example on GitHub Actions with both the `ubuntu-20.04` and `ubuntu-22.04` images. Both work without issues. I'm unable to reproduce this issue.

Since no further action is possible, I'm closing this optimistically. Please feel free to reopen / submit new issue if you're able to provide a reproducer.

**Closed by xJonathanLEI** 2023-07-03 13:15 UTC
