### ISSUE TITLE
`validate_invocation` and `fee_transfer_invocation` fields don't have to be `Option` in `TransactionTrace` types

### ISSUE THREAD

**Issue by tdelabro** [xJonathanLEI/starknet-rs#536] opened 2024-01-12 15:00 UTC
```rust
/// The execution trace of an invoke transaction.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InvokeTransactionTrace {
    pub validate_invocation: Option<FunctionInvocation>,
    pub execute_invocation: ExecuteInvocation,
    pub fee_transfer_invocation: Option<FunctionInvocation>,
    /// The state diffs induced by the transaction
    pub state_diff: Option<StateDiff>,
}
```
`validate_invocation` and `fee_transfer_invocation` are `Option`, but if we look into blockifier
```rust
/// Contains the information gathered by the execution of a transaction.
#[derive(Debug, Default, Eq, PartialEq)]
#[cfg_attr(feature = "parity-scale-codec", derive(Encode, Decode))]
pub struct TransactionExecutionInfo {
    /// Transaction validation call info; [None] for `L1Handler`.
    pub validate_call_info: Option<CallInfo>,
    /// Transaction execution call info; [None] for `Declare`.
    pub execute_call_info: Option<CallInfo>,
    /// Fee transfer call info; [None] for `L1Handler`.
    pub fee_transfer_call_info: Option<CallInfo>,
    /// The actual fee that was charged (in Wei).
    pub actual_fee: Fee,
    /// Actual execution resources the transaction is charged for,
    /// including L1 gas and additional OS resources estimation.
    pub actual_resources: ResourcesMapping,
    /// Error string for reverted transactions; [None] if transaction execution was successful.
    // TODO(Dori, 1/8/2023): If the `Eq` and `PartialEq` traits are removed, or implemented on all
    //   internal structs in this enum, this field should be `Option<TransactionExecutionError>`.
    pub revert_error: Option<String>,
}
```
we can see that `validate_call_info` and `fee_transfer_call_info` are only `None` for `L1Handler` transactions.

Based on this I think we can those two fields in `InvokeTransactionTrace` and the other tx type no being an `Option`.
Wdyt?

**Comment by xJonathanLEI** [comment] 2024-01-16 05:49
You're right. Looks like a bug in [starknet-jsonrpc-codegen](https://github.com/xJonathanLEI/starknet-jsonrpc-codegen). Not sure how it slipped through. I will double check.

**Comment by xJonathanLEI** [comment] 2024-01-16 05:55
OK I double checked. Actually, no. This is not a bug in `starknet-rs`. `starknet-rs` follows the official JSON-RPC specs (as it should), and the spec says [this](https://github.com/starkware-libs/starknet-specs/blob/49665932a97f8fdef7ac5869755d2858c5e3a687/api/starknet_trace_api_openrpc.json#L194-L197):

```json
"required": [
    "type",
    "execute_invocation"
]
```

which means anything other than `type` and `execute_invocation` is optional. `starknet-rs` is correctly following the specs.

**Comment by xJonathanLEI** [comment] 2024-01-16 05:58
Additionally, I can think of legitimate cases where `validate_invocation` and `fee_transfer_invocation` can be `None`: when the client requests a simulation with `SKIP_VALIDATE` and/or `SKIP_FEE_CHARGE`. So the spec isn't wrong either.

So it comes down to "why would `blockifier` implement it this way". Well, I don't know.. But I'm pretty sure at this point that this is _not_ a bug in `starknet-rs`. So I'm closing this issue here. Please feel free to reopen if you disagree. Thanks!

**Closed by xJonathanLEI** 2024-01-16 05:58 UTC

**Comment by tdelabro** [comment] 2024-01-16 12:54
I think you are right @xJonathanLEI. Thanks for doing the research and explanation!
