### ISSUE TITLE
Deploy transaction has been deprecated

### ISSUE THREAD

**Issue by omarespejel** [xJonathanLEI/starknet-rs#270] opened 2023-01-14 23:36 UTC
## Problem
The `deploy` transaction has been deprecated. 

## Nice to have
Other SDKs, e.g. [starknet.py](https://starknetpy.readthedocs.io/en/latest/guide.html#using-universal-deployer-contract-udc) which uses a `Deployer` object, implemented ways to easily deploy and get the address of the deployed contract (on the back, they are invoking the UDC). As far as I know, `starknet-rs` hasn't had a similar implementation yet.

## Contributions
I could help set up a similar implementation. The main issue would be, how can I get the information in an `event` using `starknet-rs`? We would need to get the address from the events in the transaction to the UDC (screenshot below).

<img width="1346" alt="image" src="https://user-images.githubusercontent.com/4755430/212501681-706fdb1e-3cc7-496e-9955-ff39bdd39137.png">

**Comment by xJonathanLEI** [comment] 2023-01-15 04:13
Hey thanks for the issues and PRs :) I will take a look shortly.

For this issue specifically, do you think it's a duplicate of #232? I plan to do a full revamp of contract deployment and the `Account` trait.

**Comment by xJonathanLEI** [comment] 2023-01-16 03:50
Closing this optimistically as a duplicate of #232. Please feel free to re-open otherwise.

**Closed by xJonathanLEI** 2023-01-16 03:50 UTC
