### ISSUE TITLE
Decompress public key for stark

### ISSUE THREAD

**Issue by rhobro** [xJonathanLEI/starknet-rs#70] opened 2022-02-22 16:07 UTC
Hi there,

Following from [issue](https://github.com/xJonathanLEI/starkware-crypto-rs/issues/10), how can I use starknet to "decompress" the public key as Jonathan suggested?

Thanks

**Comment by xJonathanLEI** [comment] 2022-02-23 02:45
`starknet-crypto` _does_ contain the logic of decompressing public keys as it needs to do that for verifying signatures. See [this line](0xaE6EC9C69e25A5Dd29c4C7183215940132e2eFbd).

However as of today, this functionality is an implementation detail and not exposed as part of the public API. If you need to use it, the best way to do that today would be to fork this repository and expose the function yourself.

**Comment by xJonathanLEI** [comment] 2022-02-23 16:40
Optimistically closing this. Feel free to re-open if you have further questions on the topic.

**Closed by xJonathanLEI** 2022-02-23 16:40 UTC

**Comment by xJonathanLEI** [comment] 2022-02-24 17:24
Hi @rhobro I noticed you just forked our library, and just want to remind you that we just discovered a critical bug which causes the decimal representation of `FieldElement` to be incorrect. This bug is currently tracked as https://github.com/xJonathanLEI/starknet-rs/issues/74.

So if you print out the coordinates you get, you'll be getting incorrect numbers. You might want to incorporate the fix once it's implemented (very soon).

**Comment by xJonathanLEI** [comment] 2022-02-24 17:31
Sure thing :)

**Comment by xJonathanLEI** [comment] 2022-02-24 17:53
The commit fixing the issue is on `master` now @rhobro

**Comment by rhobro** [comment] 2022-02-24 17:54
That was rapid. Thanks man.

**Comment by rhobro** [comment] 2022-02-25 11:31
I forked it and exposed just the logic to get the y coordinate which I found in EcPoint::from_x. It is amazing that it was the same logic I found on the starkware website.

Out of interest @xJonathanLEI, would it be possible to be able to do arithmetic with references to FieldElements rather than having to clone them to pass into a function?

**Comment by xJonathanLEI** [comment] 2022-02-25 13:43
Yeah I'd expect the same logic to be used everywhere. I guess that means we have a correct implementation :)

As for using references for arithmetic, yes we will be implementing ops that take references alongside the existing ones. **However**, I'd say you shouldn't worry about this for performance reasons (I'm presuming you're trying to do it for performance reasons; please ignore me if that's not the case :)), as this will be taken care of by the Rust optimizer.

**Comment by rhobro** [comment] 2022-02-26 07:51
I was trying to do it for performance reasons 😳. How can the rust optimiser solve it?

**Comment by xJonathanLEI** [comment] 2022-02-26 08:17
Obviously you'd need to benchmark for your case yourself, but generally speaking, if ownership is taken without being used, the compiler _might_ turn it into a reference instead, depending on a lot of factors including the size of the struct in question.

**Comment by rhobro** [comment] 2022-02-26 13:47
Ok. Thanks for the info.
